Removing outdated statements/correcting some grammar and wording
niwanetwork/niwa-website pull request #40
Opened 2021-05-02 20:33 UTC by AlexBot2004

2021-05-03 03:27 UTC, Elaeagnifolia requested changes

2021-05-03 03:27 UTC, Elaeagnifolia commented on data/members.json
> +      "description": "Founded in early 2010 by Tacopill, WikiBound strives to create a detailed database on the Mother/EarthBound games, a quaint series only having two games officially released outs
Extra period after Japan.

2021-05-04 04:15 UTC, Elaeagnifolia commented
Also since PR #42 was merged, you will want to pull the most recent changes that update this file.

2021-07-05 22:18 UTC, KevinPayravi approved these changes

2021-07-05 22:18 UTC, merged